export const DEFAULT_THEME_CONFIG = {
  global: {},
  local: {}
}

export const YUI_THEME_USER_CONFIG = 'YUI_THEME_USER_CONFIG'

export const YUI_THEME_PREVIEW_CONFIG = 'YUI_THEME_PREVIEW_CONFIG'

export const ACTION_DOWNLOAD_THEME = 'YUI_THEME_ACTION_DOWNLOAD'

export const ACTION_APPLY_THEME = 'YUI_THEME_ACTION_ALLPY_CSS'

export const ACTION_COMPONECT_SELECT = 'YUI_THEME_ACTION_COMPONECT_SELECT'

export const ACTION_USER_CONFIG_UPDATE = 'YUI_THEME_USER_CONFIG_UPDATE'
