<template>
  <div class="app" style="height: 500px; overflow: auto">
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <div>fsdfds</div>
    <y-backtop target=".app" />
  </div>
</template>

<script>
export default {
  data() {
    return {
      visible: false
    }
  }
}
</script>
