/* Automatically generated by './build/bin/build-entry.js' */

import Input from '../packages/input'
import Form from '../packages/form'
import FormItem from '../packages/form-item'
import Icon from '../packages/icon'

const components = [
  Input,
  Form,
  FormItem,
  Icon
]

const install = function (Vue, opts = {}) {
  components.forEach((component) => {
    Vue.component(component.name, component)
  })

  Vue.prototype.$YUI = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  }
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '2.15.6',
  install,
  Input,
  Form,
  FormItem,
  Icon
}
